services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  Visol\Permissions\ContextMenu\ManagePermissionsItemProvider:
    tags:
      - name: backend.contextmenu.itemprovider
